
name: sample-workflow

on:
workflow-dispatch:
workflow
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name : Run one line
      run : echo Hello World!
    steps:
      - uses: actions/checkout@v1

      - name: setup
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: install and setup config
        run: npm install

      - name: lint
        run: npm run lint:format

      - name: test
        run: npm test