name: New test 2
'on':
  push:
    branches:
      - main
  workflow_dispatch: 
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set up JDK 18
        with:
          java-version: 18.0.2+101
          distribution: temurin
          cache: maven
          server-id: github
      - name: Build with Maven
        run: |
          mvn clean
          mvn compile
          mvn test
