name: Java CI with Maven
'on':
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Build with Maven
        run: |
          mvn clean
          mvn compile
          mvn test
