# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18.0.2+101'
        distribution: 'temurin'
        cache: maven
        server-id: github 
        settings-path: ${{ github.workspace }} 
    - name:  Install Google Chrome 
      run:   |
              chmod +x ./scripts/InstallChrome.sh
                          ./scripts/InstallChrome.sh 
    - name: Build with Maven
      run: |
        mvn clean
        mvn compile
        mvn test
